(() => {
  "use strict";
  const STORAGE_KEY="notesVaultEnvelopeV1",DECOY_KEY="notesVaultDecoyV31",ITERATIONS=350000;
  const $=id=>document.getElementById(id);
  const realApp=$("realApp"),decoyView=$("decoyView"),welcomeView=$("welcomeView"),unlockView=$("unlockView"),vaultView=$("vaultView"),lockBtn=$("lockBtn"),addPanel=$("addPanel"),chatList=$("chatList"),emptyState=$("emptyState"),countLabel=$("countLabel"),searchInput=$("searchInput"),categoryFilters=$("categoryFilters");
  let unlockedPin=null,vaultData={chats:[],settings:{}},currentCategory="Tous";
  function setMsg(id,text,type=""){const el=$(id);el.textContent=text;el.className=`msg ${type}`}
  function bytesToB64(bytes){let s="";for(const b of bytes)s+=String.fromCharCode(b);return btoa(s)}
  function b64ToBytes(s){const bin=atob(s);return Uint8Array.from(bin,c=>c.charCodeAt(0))}
  function toB64Url(text){return bytesToB64(new TextEncoder().encode(text)).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
  function fromB64Url(s){s=s.replace(/-/g,"+").replace(/_/g,"/");while(s.length%4)s+="=";return new TextDecoder().decode(b64ToBytes(s))}
  async function deriveKey(pin,salt,iterations=ITERATIONS){const baseKey=await crypto.subtle.importKey("raw",new TextEncoder().encode(pin),"PBKDF2",false,["deriveKey"]);return crypto.subtle.deriveKey({name:"PBKDF2",salt,iterations,hash:"SHA-256"},baseKey,{name:"AES-GCM",length:256},false,["encrypt","decrypt"])}
  async function encryptVault(pin,data,existingSaltB64=null){const salt=existingSaltB64?b64ToBytes(existingSaltB64):crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await deriveKey(pin,salt),plaintext=new TextEncoder().encode(JSON.stringify(data)),cipher=await crypto.subtle.encrypt({name:"AES-GCM",iv},key,plaintext);return{v:1,kdf:"PBKDF2-SHA256",iterations:ITERATIONS,salt:bytesToB64(salt),iv:bytesToB64(iv),data:bytesToB64(new Uint8Array(cipher))}}
  async function decryptVault(pin,envelope){const key=await deriveKey(pin,b64ToBytes(envelope.salt),Number(envelope.iterations)||ITERATIONS),plain=await crypto.subtle.decrypt({name:"AES-GCM",iv:b64ToBytes(envelope.iv)},key,b64ToBytes(envelope.data)),obj=JSON.parse(new TextDecoder().decode(plain));if(!obj||!Array.isArray(obj.chats))throw new Error("Invalid vault");obj.settings||={};for(const c of obj.chats)c.category||="Autre";return obj}
  function getEnvelope(){try{const raw=localStorage.getItem(STORAGE_KEY);return raw?JSON.parse(raw):null}catch{return null}}
  function saveEnvelope(e){localStorage.setItem(STORAGE_KEY,JSON.stringify(e))}
  function showDecoy(){unlockedPin=null;vaultData={chats:[],settings:{}};realApp.classList.add("hidden");decoyView.classList.remove("hidden")}
  function lock(){unlockedPin=null;vaultData={chats:[],settings:{}};$("unlockPin").value="";if(localStorage.getItem(DECOY_KEY)==="1"){showDecoy();return}realApp.classList.remove("hidden");decoyView.classList.add("hidden");vaultView.classList.add("hidden");welcomeView.classList.add("hidden");unlockView.classList.remove("hidden");lockBtn.classList.add("hidden");$("backToDecoyBtn").classList.add("hidden")}
  function showUnlockFromDecoy(){realApp.classList.remove("hidden");decoyView.classList.add("hidden");vaultView.classList.add("hidden");welcomeView.classList.add("hidden");unlockView.classList.remove("hidden");lockBtn.classList.add("hidden");$("backToDecoyBtn").classList.remove("hidden")}
  function showWelcome(){unlockedPin=null;realApp.classList.remove("hidden");decoyView.classList.add("hidden");vaultView.classList.add("hidden");unlockView.classList.add("hidden");welcomeView.classList.remove("hidden");lockBtn.classList.add("hidden")}
  function showVault(){realApp.classList.remove("hidden");decoyView.classList.add("hidden");welcomeView.classList.add("hidden");unlockView.classList.add("hidden");vaultView.classList.remove("hidden");lockBtn.classList.remove("hidden");$("decoyToggle").checked=localStorage.getItem(DECOY_KEY)==="1";renderCategories();renderChats()}
  async function persist(){const old=getEnvelope(),envelope=await encryptVault(unlockedPin,vaultData,old?.salt||null);saveEnvelope(envelope);return envelope}
  function normalizeChatUrl(value){try{const url=new URL(value.trim());if(url.protocol!=="https:"||!["chatgpt.com","www.chatgpt.com"].includes(url.hostname)||!/^\/c\/[^/?#]+/.test(url.pathname))return null;return`https://chatgpt.com${url.pathname}`}catch{return null}}
  function categories(){const set=new Set(vaultData.chats.map(c=>c.category||"Autre"));return["Tous",...Array.from(set).sort((a,b)=>a.localeCompare(b,"fr"))]}
  function renderCategories(){const cats=categories();if(!cats.includes(currentCategory))currentCategory="Tous";categoryFilters.innerHTML="";for(const cat of cats){const b=document.createElement("button");b.className=`chip ${cat===currentCategory?"active":""}`;b.textContent=cat;b.onclick=()=>{currentCategory=cat;renderCategories();renderChats()};categoryFilters.appendChild(b)}}
  function filteredChats(){const q=searchInput.value.trim().toLocaleLowerCase("fr");return[...vaultData.chats].filter(c=>currentCategory==="Tous"||(c.category||"Autre")===currentCategory).filter(c=>!q||`${c.label} ${c.category||""}`.toLocaleLowerCase("fr").includes(q)).sort((a,b)=>(b.createdAt||0)-(a.createdAt||0))}
  function renderChats(){chatList.innerHTML="";const chats=filteredChats();emptyState.classList.toggle("hidden",chats.length>0);countLabel.textContent=`${vaultData.chats.length} conversation${vaultData.chats.length>1?"s":""}`;for(const chat of chats){const node=$("chatItemTemplate").content.firstElementChild.cloneNode(true);node.querySelector(".chatName").textContent=chat.label;node.querySelector(".chatCategory").textContent=chat.category||"Autre";node.querySelector(".chatOpen").onclick=()=>{window.open(chat.url,"_blank","noopener");lock()};node.querySelector(".chatMenu").onclick=async()=>{const a=prompt(`Options pour "${chat.label}"\n\n1 = Renommer\n2 = Changer la catégorie\n3 = Retirer du coffre\n\nTape 1, 2 ou 3 :`);if(a==="1"){const n=prompt("Nouveau nom :",chat.label);if(n&&n.trim()){chat.label=n.trim().slice(0,80);await persist();renderChats()}}else if(a==="2"){const n=prompt("Nouvelle catégorie :",chat.category||"Autre");if(n&&n.trim()){chat.category=n.trim().slice(0,40);await persist();renderCategories();renderChats()}}else if(a==="3"){if(confirm(`Retirer "${chat.label}" de Notes ?\n\nLe chat ChatGPT lui-même ne sera PAS supprimé.`)){vaultData.chats=vaultData.chats.filter(x=>x.id!==chat.id);await persist();renderCategories();renderChats()}}};chatList.appendChild(node)}}
  async function createVault(){const pin=$("newPin").value.trim(),confirmPin=$("confirmPin").value.trim();if(!/^\d{6,}$/.test(pin)){setMsg("welcomeMsg","Choisis au moins 6 chiffres.","err");return}if(pin!==confirmPin){setMsg("welcomeMsg","Les deux codes ne correspondent pas.","err");return}vaultData={chats:[],settings:{}};unlockedPin=pin;saveEnvelope(await encryptVault(pin,vaultData));$("newPin").value="";$("confirmPin").value="";showVault()}
  async function unlockVault(){const pin=$("unlockPin").value.trim(),envelope=getEnvelope();if(!envelope){showWelcome();return}try{vaultData=await decryptVault(pin,envelope);unlockedPin=pin;$("unlockPin").value="";setMsg("unlockMsg","");showVault()}catch{setMsg("unlockMsg","Code incorrect.","err");$("unlockPin").select()}}
  function encodeEnvelope(e){return toB64Url(JSON.stringify(e))}
  function parseImportedValue(value){const trimmed=value.trim();if(!trimmed)throw new Error();let payload=trimmed;try{const url=new URL(trimmed),hash=new URLSearchParams(url.hash.replace(/^#/,""));payload=hash.get("vault")||trimmed}catch{const m=trimmed.match(/(?:^|[#?&])vault=([^&]+)/);if(m)payload=m[1]}const e=JSON.parse(fromB64Url(payload));if(!e||e.v!==1||!e.salt||!e.iv||!e.data)throw new Error();return e}
  async function importVaultFromText(){try{saveEnvelope(parseImportedValue($("importText").value));$("importText").value="";setMsg("welcomeMsg","Importé. Entre maintenant ton code.","ok");setTimeout(lock,450)}catch{setMsg("welcomeMsg","Ce lien/code n'est pas valide.","err")}}
  async function saveChat(){const label=$("chatLabel").value.trim(),category=($("chatCategory").value.trim()||"Autre").slice(0,40),url=normalizeChatUrl($("chatUrl").value);if(!label){setMsg("addMsg","Mets un petit nom discret.","err");return}if(!url){setMsg("addMsg","Colle un lien ChatGPT du type chatgpt.com/c/…","err");return}const ex=vaultData.chats.find(x=>x.url===url);if(ex){ex.label=label;ex.category=category}else vaultData.chats.push({id:crypto.randomUUID(),label,category,url,createdAt:Date.now()});await persist();$("chatLabel").value="";$("chatCategory").value="";$("chatUrl").value="";addPanel.classList.add("hidden");setMsg("addMsg","Enregistré.","ok");renderCategories();renderChats()}
  async function copyText(text,msgId){try{await navigator.clipboard.writeText(text);setMsg(msgId,"Copié ✦","ok")}catch{prompt("Copie ce texte :",text)}}
  async function copyPrivateLink(){const envelope=await persist();if(["http:","https:"].includes(location.protocol)){const base=`${location.origin}${location.pathname}`;await copyText(`${base}#vault=${encodeEnvelope(envelope)}`,"syncMsg")}else setMsg("syncMsg","Héberge d'abord l'app pour avoir un lien.","err")}
  async function copyBackup(){await copyText(encodeEnvelope(await persist()),"syncMsg")}
  function maybeImportFromHash(){const p=new URLSearchParams(location.hash.replace(/^#/,"")),payload=p.get("vault");if(!payload)return false;try{saveEnvelope(parseImportedValue(payload));history.replaceState(null,"",location.pathname+location.search);return true}catch{return false}}
  $("createVaultBtn").onclick=createVault;$("unlockBtn").onclick=unlockVault;$("unlockPin").onkeydown=e=>{if(e.key==="Enter")unlockVault()};$("importBtn").onclick=importVaultFromText;$("resetLocalBtn").onclick=()=>{if(confirm("Effacer le coffre de CET appareil ?\n\nTes chats ChatGPT ne seront pas supprimés.")){localStorage.removeItem(STORAGE_KEY);localStorage.removeItem(DECOY_KEY);showWelcome()}};lockBtn.onclick=lock;$("addBtn").onclick=()=>{addPanel.classList.toggle("hidden");if(!addPanel.classList.contains("hidden"))setTimeout(()=>$("chatLabel").focus(),0)};$("cancelAddBtn").onclick=()=>addPanel.classList.add("hidden");$("saveChatBtn").onclick=saveChat;searchInput.oninput=renderChats;$("copyPrivateLinkBtn").onclick=copyPrivateLink;$("copyBackupBtn").onclick=copyBackup;$("decoyToggle").onchange=e=>{localStorage.setItem(DECOY_KEY,e.target.checked?"1":"0");setMsg("privacyMsg",e.target.checked?"Mode leurre activé. À la prochaine ouverture, tape 5 fois sur « Notes ».":"Mode leurre désactivé.","ok")};$("backToDecoyBtn").onclick=showDecoy;
  let taps=0,timer=null;$("secretTap").onclick=()=>{taps++;clearTimeout(timer);timer=setTimeout(()=>taps=0,1600);if(taps>=5){taps=0;showUnlockFromDecoy()}};
  document.addEventListener("visibilitychange",()=>{if(document.hidden&&unlockedPin)lock()});window.addEventListener("pagehide",()=>{unlockedPin=null;vaultData={chats:[],settings:{}}});
  if("serviceWorker" in navigator&&location.protocol.startsWith("http"))navigator.serviceWorker.register("service-worker.js").catch(()=>{});
  const imported=maybeImportFromHash();if(getEnvelope())lock();else showWelcome();if(imported)setMsg("unlockMsg","Coffre importé sur cet appareil. Entre ton code.","ok");
})();